image:
    - Visual Studio 2015
environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
install:
    - "%PYTHON%\\python.exe -m pip install --upgrade setuptools pip"
    - "%PYTHON%\\python.exe -m pip install --upgrade virtualenv"
    - "%PYTHON%\\python.exe -m pip --version"
    - "%PYTHON%\\python.exe -m virtualenv --version"
    - "git.exe --version"
    - "%PYTHON%\\python.exe -m pip install --upgrade flake8==3.5.0 pylint==1.9.3 pytest==3.7.4"
    - "%PYTHON%\\python.exe -m pip install --upgrade pytest-flake8==1.0.2 pytest-pylint==0.12.3"
    - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
build: off
test_script:
    - "%PYTHON%\\python.exe -m pytest"
skip_branch_with_pr: true
