dist: trusty
sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip --version
    - virtualenv --version
    - git --version
before_script:
    - pip install --upgrade flake8==3.5.0 pylint==1.9.3 pytest==3.7.4 pytest-flake8==1.0.2 pytest-pylint==0.12.3
    - pip install -r requirements.txt
script:
    - python -m pytest
